### ISSUE TITLE
Add Missing Dependency (first)

### ISSUE THREAD

**Issue by mtbutler07** [jeremyschulman/netcfgbu#29]
### Description
netcfgbu fails to run because the `first` package is missing from the requirements.txt file

### Environment
* Python version: 3.8.1
* OS: Linux - RHEL7 

### Steps to Reproduce
1.  `$ git clone https://github.com/jeremyschulman/netcfgbu.git`
2.  `$ cd netcfgbu`
3.  `$ python3.8 setup.py install --user`
4.  `$ netcfgbu`

### Expected Behavior
netcfg usage instructions
```bash
[3667673@lab-auto-dev netcfgbu]$ netcfgbu
Usage: netcfgbu [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  backup     Backup network configurations.
  inventory  [ls, build, ...]
  lint       Remove unwanted content from network config files.
  login      Verify SSH login to devices.
  probe      Probe device for SSH reachablility.
```

### Observed Behavior

ModuleNotFoundError occurred

```bash
[marcus@lab-auto-dev netcfgbu]$ netcfgbu
Traceback (most recent call last):
  File "/home/3667673/.local/bin/netcfgbu", line 4, in <module>
    __import__('pkg_resources').run_script('netcfgbu==0.2.0', 'netcfgbu')
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/3667673/.local/lib/python3.8/site-packages/netcfgbu-0.2.0-py3.8.egg/EGG-INFO/scripts/netcfgbu", line 27, in <module>
ModuleNotFoundError: No module named 'first'
```

**Comment by jeremyschulman** [comment]
merged to v0.2.1
